name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tabepal_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd backend
        npm install
        
    - name: Run Database Migrations
      run: |
        cd backend
        npx prisma migrate deploy
        
    - name: Run Individual Tests
      run: |
        cd backend
        npm test backend/__tests__/auth.test.js
        npm test backend/__tests__/items.test.js
        npm test backend/__tests__/shopList.test.js
        # Add other test files as needed
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/tabepal_test
        JWT_SECRET: test_secret_key
        NODE_ENV: test

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm test